# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6228cc445719f2e3026797792338da109b0482824a7260d220f5102420ef27bea4de905cb82cf63c9ec1eb791969864bb8b27647a6d6aa6ea9e25008ca030769

test:
  secret_key_base: b2060f64e591511a3391006b4c121ffb406e8b77884253025640b5878f150fe6ccc3472531179f87e6177c80d703e3ab71db0aaa7f1d5557fca6533b5b44d034

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
